apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  labels:
    app: wil-playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wil-playground
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground-v1
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
      - name: wil-playground-v2
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
