apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
  labels:
    app: wil-playground
spec:
  replicas: 2  # Total replicas across versions
  selector:
    matchLabels:
      app: wil-playground
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
        - name: wil-playground
          image: wil42/playground:v1  # Starting with v1
          ports:
            - containerPort: 8888
          # Image will change in the same deployment to manage both versions
          imagePullPolicy: Always
