apiVersion: v1
kind: Service
metadata:
  name: dev-app-service
spec:
  type: NodePort # Change to NodePort or LoadBalancer if you need external access
  selector:
    app: dev-app
  ports:
    - port: 8888
      targetPort: 8888
