apiVersion: v1
kind: Service
metadata:
  name: wil-playground-v1
spec:
  type: NodePort
  selector:
    app: wil-playground
    version: v1
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088
---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground-v2
spec:
  type: NodePort
  selector:
    app: wil-playground
    version: v2
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30089
