apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  type: NodePort # Change to NodePort or LoadBalancer if you need external access
  selector:
    app: dev-app
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088  # NodePort to access the service externally (example: 30088)

