apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  selector:
    app: dev
  ports:
    - protocol: TCP
      port: 8888 # The port your app runs on
      targetPort: 8888 # The container’s port
      nodePort: 30080 # The port to expose on your host
  type: NodePort
